### ISSUE TITLE
Failing to upload/save files

### ISSUE THREAD

**Issue by Typhonragewind** [rishikanthc/Scriberr#2]
Hi! Love where this project is headed, but i'm having some trouble getting it to work.

**Issue:** Files are not saved to /scriberr/audio/ after upload. because of this, no audio processing is happening

**Installation method:** Docker-compose example in repo

**Attempts to fix:**
- verified file permissions multiple times. Even with 777 permissisons, it does not work
- tried a native docker volume instead of a bind mount, no luck either
**Note:** Between attempts to fix, I deleted the DB files to make sure it did not interfere, and cleared all browser data

**Proof of upload from container log:**
from upload file File {
2024-10-05T11:31:24.961411462Z   size: 455629,
2024-10-05T11:31:24.961418707Z   type: 'audio/ogg',
2024-10-05T11:31:24.961424662Z   name: 'WhatsApp Audio 2024-05-22 at 20.29.21_ef1bd0ae.waptt.opus',
2024-10-05T11:31:24.961447870Z   lastModified: 1728127884960
2024-10-05T11:31:24.961458093Z }

**Job error:**
Error: ENOENT: no such file or directory, open '/scriberr/audio/czoqf4b4izfaxs1.oga'
    at Object.openSync (node:fs:561:18)
    at Object.writeFileSync (node:fs:2358:35)
    at Worker.connection.host [as processFn] (file:///app/build/server/chunks/queue-C2m1Jwu2.js:43894:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Worker.processJob (/app/node_modules/bullmq/dist/cjs/classes/worker.js:455:28)
    at async Worker.retryIfFailed (/app/node_modules/bullmq/dist/cjs/classes/worker.js:640:24)

**Comment by rishikanthc** [comment]
Files will not be saved to /scriberr/audio. files are stored in a database. the /scriberr is just a temporary folder used while processing jobs. Can you open the job queue UI at http://localhost:9243/admin/queues ? That will have access to detailed logs on what's going on and will help me debug

**Comment by rishikanthc** [comment]
Closing this as it's the same issue as #3 
Fix is to create sub-directories `audio` and `transcripts` under SCRIBO_FILES
