### ISSUE TITLE
Wrong pocketbase auth token when you restart anew the containers

### ISSUE THREAD

**Issue by Pablo1107** [rishikanthc/Scriberr#29]
If you erase all the containers and volumes and start anew, the old token is saved as cookie in the browser and you get this error:

```
Auth state after loading cookie: true
Auth token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzEyMTYyNTMsImlkIjoiZnRmamcweHBrMm5hZTNkIiwidHlwZSI6ImFkbWluIn0.PBxn6jvwPlENoBD-W8T5beUFztSes2aBkQOofG4jf1c
ClientResponseError 401: The request requires valid admin authorization token to be set.
    at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async configuration (file:///app/build/server/chunks/hooks.server-dE1o57EC.js:94:23)
    at async authentication (file:///app/build/server/chunks/hooks.server-dE1o57EC.js:83:20)
    at async respond (file:///app/build/server/index.js:3859:22)
    at async Array.ssr (file:///app/build/handler.js:1272:3) {
  url: 'http://pocketbase:8080/api/collections?page=1&perPage=500&skipTotal=1',
  status: 401,
  response: {
    code: 401,
    message: 'The request requires valid admin authorization token to be set.',
    data: {}
  },
  isAbort: false,
  originalError: {
    url: 'http://pocketbase:8080/api/collections?page=1&perPage=500&skipTotal=1',
    status: 401,
    data: {
      code: 401,
      message: 'The request requires valid admin authorization token to be set.',
      data: {}
    }
  }
}
```

The workaround for this is to erase the cookies from the browser and refresh the page.

Maybe this can be fixed by getting a new token if the one saved fails like this.

**Comment by rishikanthc** [comment]
Yeah, I'm aware of this. I'll fix this in the next release. It has actually been a major annoyance during development.

**Comment by SpirusNox** [comment]
@rishikanthc, do you know if this has been fixed in the newest code on the repo? Or is it still getting added on in the latest release?

**Comment by rishikanthc** [comment]
No it's still not fixed completely. I tried to fix this but couldn't get it working. So we need to fix this in the upcoming release.

**Comment by SpirusNox** [comment]
Sounds good. Let me know whenever there is a list of things to work on.

**Comment by rishikanthc** [comment]
@SpirusNox working on the list. I know you're waiting on it. Sorry for the delay. 
I'm getting married tomorrow xD so things are a bit crazy.

**Comment by SpirusNox** [comment]
@rishikanthc you are good my dude. Take your time. Whenever you are ready

**Comment by SpirusNox** [comment]
@rishikanthc and congratulations!

**Comment by SpirusNox** [comment]
@Pablo1107, I fixed this in the latest nightly version. I think we are practically there for a new release. But give the new nightly version a try. It will now properly take you to a login page if your token is expired, and if you are active, it will renew your token. Let me know how it goes. I will close this out on Monday if there seems to be no issue.

**Comment by Pablo1107** [comment]
> [@Pablo1107](https://github.com/Pablo1107), I fixed this in the latest nightly version. I think we are practically there for a new release. But give the new nightly version a try. It will now properly take you to a login page if your token is expired, and if you are active, it will renew your token. Let me know how it goes. I will close this out on Monday if there seems to be no issue.

Hey, didn't had time to retest this, but glad you made a fix for it. If I ever revisit the project, I'll test if this works.

**Comment by SpirusNox** [comment]
We certainly hope you will! There are some great features coming up and would love to get feedback as we progress. Thank you for responding!
