### ISSUE TITLE
Error 0.3.0 - Failed to authenticate

### ISSUE THREAD

**Issue by CyberSardinha** [rishikanthc/Scriberr#36]
I have tried to install the 0.3.0 version and I get this error the first time it runs.
I had the 0.2.1 before installed and it did work.

Any ideas what the problem is? I've checked all the password and changed them again and they are correct.

Thanks

> "resolve" is imported from external module "chart.js/helpers" but never used in "src/hooks.server.ts".
> "execSync" and "spawn" are imported from external module "child_process" but never used in "src/lib/wizardQueue.ts" and "src/lib/queue.ts".
> 
> node:internal/event_target:1090
>   process.nextTick(() => { throw err; });
>                            ^
> ClientResponseError 400: Failed to authenticate.
>     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async AdminService.authWithPassword (file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:10912)
>     at async file:///app/.svelte-kit/output/server/chunks/wizardQueue.js:133:1 {
>   url: 'http://192.168.0.2:5170/api/admins/auth-with-password',
>   status: 400,
>   response: { code: 400, message: 'Failed to authenticate.', data: {} },
>   isAbort: false,
>   originalError: {
>     url: 'http://192.168.0.2:5170/api/admins/auth-with-password',
>     status: 400,
>     data: { code: 400, message: 'Failed to authenticate.', data: {} }
>   }
> }
> 
> Node.js v22.10.0
> node:internal/modules/cjs/loader:1252
>   throw err;
>   ^
> 
> Error: Cannot find module '/app/build'
>     at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
>     at Function._load (node:internal/modules/cjs/loader:1075:27)
>     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
>     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
>     at node:internal/main/run_main_module:36:49 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
>

**Comment by rowanfuchs** [comment]
I've got the same issue.

**Comment by rowanfuchs** [comment]
So the issue is that the default docker compose doesn't work out of the box, you cant connect to pocketbase if you don't share a network amongst its services and properly name them, please update the documentation, here is my solution:

```
services:
  scriberr:
    container_name: scriberr
    image: ghcr.io/rishikanthc/scriberr:0.3.0
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
      pocketbase:
        condition: service_started

    ports:
      - "3000:3000" # Scriberr UI
      - "9243:9243" # Optionally expose JobQueue UI
      #- "8080:8080" # Optionally expose Database Management UI
    environment:
      - OPENAI_API_KEY=
      - OPENAI_ENDPOINT=
      - OPENAI_MODEL=
      - OPENAI_ROLE=user
      - POCKETBASE_ADMIN_EMAIL=admin@example.com
      - POCKETBASE_ADMIN_PASSWORD=1234567890
      - POCKETBASE_URL=http://pocketbase:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SCRIBO_FILES=/scriberr
      - DEV_MODE=false
      - NVIDIA=false # set to true if you have one
      - CONCURRENCY=1 # Adjut cautiously according to hardware limits
    volumes:
      - ./scriberr/pb_data:/app/db
      - ./scriberr:/scriberr
      - ./scriberr/models:/models
    networks:
      - scriberr
    
  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - ./.dockerdata/redis:/data
    networks:
      - scriberr

  pocketbase:
    image: ghcr.io/rishikanthc/pocketbase:22.22
    container_name: pocketbase
    environment:
      - POCKETBASE_ADMIN_EMAIL=admin@example.com  # Replace with your admin email
      - POCKETBASE_ADMIN_PASSWORD=1234567890  # Replace with your admin password
    ports:
      - "8080:8080"  # Expose PocketBase on port 8080
    volumes:
      - ./pb_data:/pb/pb_data  # Mount the PocketBase data directory for persistence
    restart: unless-stopped  # Always restart unless explicitly stopped
    networks:
      - scriberr
    
networks:
  scriberr:
    external: false
```

tip, keep the docker compose as minimal as possible i.e. optional fields shouldn't be mentioned other than in the following documentation.

**Comment by SpirusNox** [comment]
I believe this has already been fixed in the latest release. But even if it's not, the newest version in the repo has definitely fixed it. Check it out! 

And if you have more issues. Please create a new issue and we can take care of that.

**Comment by babanovac1980** [comment]
This is for Unraid users
I used the latest version today and got the same issue.
Luckily, I was watching the logs and saw a complaint about the password length being at least 8 chars. I've set up my  pocketbase password initially only with 6 characters. I generated a random 16 chars password, updated it in both places (unraid's app comes without pocketbase or redis so you need those 2 as separate containers) and this went away. (I still cannot get it to work with a GPU but that's a different issue)

**Comment by SpirusNox** [comment]
Copy that. Currently the docker-compose that is listed on the website is a little out of date. I would recommend going to the readme on the github repo here and testing that out. I have never used unraid for dockers, so I do not know how to get GPU acceleration for that. But there is a docker image now in the nightly that supports nvidia GPU acceleration. But it will require a driver that is 570 or newer.

The newest nightly version does not use pocketbase at all. It went to a postgres server, which makes it easier for later development as well. So anything that is there currently will be lost.
